# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jarvisMainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 900)
        font = QtGui.QFont()
        font.setUnderline(False)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.arcLabel = QtWidgets.QLabel(Dialog)
        self.arcLabel.setGeometry(QtCore.QRect(480, 220, 521, 311))
        self.arcLabel.setStyleSheet("border-radius:200px;\n"
"background-color: transparent;")
        self.arcLabel.setText("")
        self.arcLabel.setPixmap(QtGui.QPixmap("C:\\Users\\Alexander Binny\\Downloads\\robotsconcept_ga.gif"))
        self.arcLabel.setScaledContents(True)
        self.arcLabel.setObjectName("arcLabel")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(-10, 580, 1291, 321))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:\\Users\\Alexander Binny\\Downloads\\vecteezy_futuristic-technological-grid-background-digital-futurist_7207818.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.terminaloutputbox = QtWidgets.QPlainTextEdit(Dialog)
        self.terminaloutputbox.setGeometry(QtCore.QRect(0, 580, 1011, 321))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        self.terminaloutputbox.setFont(font)
        self.terminaloutputbox.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"background-color:transparent;\n"
"color:white;")
        self.terminaloutputbox.setPlainText("")
        self.terminaloutputbox.setObjectName("terminaloutputbox")
        self.speaking = QtWidgets.QLabel(Dialog)
        self.speaking.setGeometry(QtCore.QRect(90, 240, 261, 251))
        self.speaking.setText("")
        self.speaking.setPixmap(QtGui.QPixmap("C:\\Users\\Alexander Binny\\Downloads\\alexa-amazon.gif"))
        self.speaking.setScaledContents(True)
        self.speaking.setObjectName("speaking")
        self.listening = QtWidgets.QLabel(Dialog)
        self.listening.setGeometry(QtCore.QRect(60, 250, 321, 271))
        self.listening.setStyleSheet("background-color:transparent;")
        self.listening.setText("")
        self.listening.setPixmap(QtGui.QPixmap("C:\\Users\\Alexander Binny\\Downloads\\Voice Recording Animation.gif"))
        self.listening.setScaledContents(True)
        self.listening.setObjectName("listening")
        self.sleep = QtWidgets.QLabel(Dialog)
        self.sleep.setGeometry(QtCore.QRect(60, 240, 331, 291))
        self.sleep.setText("")
        self.sleep.setPixmap(QtGui.QPixmap("C:\\Users\\Alexander Binny\\Downloads\\Artificial Intelligence design.gif"))
        self.sleep.setScaledContents(True)
        self.sleep.setObjectName("sleep")
        self.exitbutton = QtWidgets.QPushButton(Dialog)
        self.exitbutton.setGeometry(QtCore.QRect(390, 520, 141, 51))
        self.exitbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitbutton.setStyleSheet("border-image: url(C:/Users/Alexander Binny/Downloads/20696460.jpg);\n"
"background-color:transparent;")
        self.exitbutton.setText("")
        self.exitbutton.setObjectName("exitbutton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 30, 700, 171))
        self.label.setStyleSheet("border-image: url(C:/Users/Alexander Binny/Downloads/output-onlinetexttools.png);\n"
"background-color:transparent;")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
